version: "3.9"

services:
  tg_bot:
    build: ./tg_bot
    container_name: tg_bot
    restart: always
    env_file:
      - ./tg_bot/.env
    ports:
      - "8000:8000"
    depends_on:
      - back

  back:
    build: ./back
    container_name: back
    restart: always
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  front:
    build: ./front
    container_name: front
    restart: unless-stopped
    ports:
      - "4200:4200"
    working_dir: /app
    volumes:
      - ./front:/app
      - /app/node_modules
